import type { RoleRow } from './screens/RolesScreen';
import type { Asset as AssetRow } from './screens/AssetsScreen';

export type RootStackParamList = {
  Login: undefined;
  ChangePassword: { forced?: boolean } | undefined;
  TwoFaEnrol: { employeeId: string; password: string };
  Home: undefined;
  More: undefined;
  Outbox: undefined;
  Notifications: undefined;
  Reports: undefined;
  ShiftReports: undefined;
  Readings: undefined;
  Assets: undefined;
  AssetDetail: { asset: AssetRow };
  History: undefined;
  Parts: undefined;
  AssetNew: undefined;
  Maintenance: undefined;
  JobCards: undefined;
  JobCardNew: { assetId?: string };
  DailyReading: { assetId: string; assetNumber: string; assetName: string };
  ShiftReport: { assetId: string; assetNumber: string; assetName: string; siteId: string; correctId?: string };
  Roles: undefined;
  RoleForm: { role?: RoleRow };
  Users: undefined;
  UserNew: undefined;
  UserRole: { userId: string; employeeId: string; currentRole: string };
  Devices: undefined;
  TwoFaSettings: undefined;
  OperationsSettings: undefined;
  Chemicals: undefined;
  SyncConflicts: undefined;
};
